### ISSUE TITLE
qri not avaible

### ISSUE THREAD

**Issue by tcamargo** [dakrone/fastri#1]
You removed qri from your tree. I prefer to use qri instead of fri+fastri-server. Is there a reason for that? Btw, i've forked fastri to readd qri.

**Comment by tcamargo** [comment]
Got my answer: fri --local.

**Comment by dakrone** [comment]
qri is automatically generated by fastri when you run 'ruby setup.rb' in the root directory of the project.

**Comment by tcamargo** [comment]
I've installed the gem and it doesn't have qri.
